routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::resource('foodplace','FoodPlaceController');

app/FoodPlace.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FoodPlace extends Model
{
    //Digunakan untuk menggunakan soft delete secara default saat menghapus data
    use SoftDeletes;
    protected $fillable = [
    	'nama','alamat','latitude','longitude','id_menu'
    ];
    protected $dates = ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FoodPlaceController.php
<?php

namespace App\Http\Controllers;

use App\FoodPlace;
use Illuminate\Http\Request;

class FoodPlaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $foodplaces = FoodPlace::orderBy('id','DESC')->paginate(5);
        return view('foodplace.index',compact('foodplaces'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('foodplace.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nama' => 'required',
            'alamat' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
            'id_menu' => 'required'
        ]);

        $foodplace = FoodPlace::create($request->all());
        return redirect()->route('foodplace.index')->with('message','Data berhasil dibuat');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function show(FoodPlace $foodplace)
    {
        return view('foodplace.show', compact('foodplace'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function edit(FoodPlace $foodplace)
    {
        return view('foodplace.edit', compact('foodplace'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FoodPlace $foodplace)
    {
        $this->validate($request, [
            'nama' => 'required',
            'alamat' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
            'id_menu' => 'required'
        ]);

        $foodplace->update($request->all());
        return redirect()->route('foodplace.index')->with('message','Berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function destroy(FoodPlace $foodplace)
    {
        $foodplace->delete();

        return redirect()->route('foodplace.index')->with('message','Data berhasil dihapus');
    }
}

resources/views/foodplace/create.blade.php
@extends('layouts.app')

@section('content')
<h4>NEW CONTENT</h4>
<form action="{{ route('foodplace.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama" class="control-label">nama</label>
        <input type="text" class="form-control" name="nama" placeholder="nama">
        @if ($errors->has('nama'))
            <span class="help-block">{{ $errors->first('nama') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat" class="control-label">address</label>
        <textarea name="alamat" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">{{ $errors->first('alamat') }}</span>
        @endif
    </div>
     <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        <label for="latitude" class="control-label">latitude</label>
        <textarea name="latitude" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has('latitude'))
            <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
    </div>
     <div class="form-group {{ $errors->has('longitude') ? 'has-error' : '' }}">
        <label for="longitude" class="control-label">longitude</label>
        <textarea name="longitude" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has(''))
            <span class="help-block">{{ $errors->first('longitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('id_menu') ? 'has-error' : '' }}">
        <label for="id_menu" class="control-label">id_menu</label>
        <textarea name="id_menu" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has(''))
            <span class="help-block">{{ $errors->first('id_menu') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/foodplace/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah Konten</h4>
<form action="{{ route('foodplace.update', $foodplace->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama" class="control-label">nama</label>
        <input type="text" class="form-control" name="nama" placeholder="nama" value="{{ $foodplace->nama }}">
        @if ($errors->has('nama'))
            <span class="help-block">{{ $errors->first('nama') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat" class="control-label">alamat</label>
        <textarea name="alamat" cols="30" rows="5" class="form-control">{{ $foodplace->alamat }}</textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">{{ $errors->first('alamat') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        <label for="latitude" class="control-label">latitude</label>
        <textarea name="latitude" cols="30" rows="5" class="form-control">{{ $foodplace->latitude }}</textarea>
        @if ($errors->has('latitude'))
            <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('longitude') ? 'has-error' : '' }}">
        <label for="longitude" class="control-label">longitude</label>
        <textarea name="longitude" cols="30" rows="5" class="form-control">{{ $foodplace->longitude }}</textarea>
        @if ($errors->has('longitude'))
            <span class="help-block">{{ $errors->first('longitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('id_menu') ? 'has-error' : '' }}">
        <label for="id_menu" class="control-label">id_menu</label>
        <textarea name="id_menu" cols="30" rows="5" class="form-control">{{ $foodplace->id_menu }}</textarea>
        @if ($errors->has('id_menu'))
            <span class="help-block">{{ $errors->first('id_menu') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/foodplace/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('foodplace.create') }}" class="btn btn-info btn-sm">Tambah Food Place</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Id_menu</th>

        </thead>
        <tbody>
            @foreach ($foodplaces as $foodplace)
                <tr>
                    <td>{{ $foodplace->id }}</td>
                     <td><a href="{{ route('foodplace.show', $foodplace->nama) }}">{{ $foodplace->nama }}</a></td>
                     <td><a href="{{ route('foodplace.show', $foodplace->alamat) }}">{{ $foodplace->alamat }}</a></td>
                      <td><a href="{{ route('foodplace.show', $foodplace->latitude) }}">{{ $foodplace->latitude }}</a></td>
                       <td><a href="{{ route('foodplace.show', $foodplace->longitude) }}">{{ $foodplace->longitude }}</a></td>
                        <td><a href="{{ route('foodplace.show', $foodplace->id_menu) }}">{{ $foodplace->id_menu }}</a></td>
                    <td>
                        <form action="{{ route('foodplace.destroy', $foodplace->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('foodplace.edit', $foodplace->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endsection

resources/views/foodplace/show.blade.php
@extends('layouts.app')

@section('content')
<h4>{{ $foodPlace->nama }}</h4>
<p>{{ $foodPlace->alamat }}</p>
<p>{{ $foodPlace->latitude }}</p>
<p>{{ $foodPlace->longitude }}</p>
<a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title>FOOD POINT - CRUD</title>
    <style>
        .martop-sm {margin-top: 15px;}
        .martop-lg {margin-top: 70px;}
    </style>
</head>
<body>
    <div class="container martop-lg">
        <div class="panel panel-default">
            <div class="panel-body">@yield('content')</div>
        </div>
    </div>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>